from fastapi import APIRouter
from app.api.v1.endpoints import auth, auth_social, profiles, discover, swipes, matches, messages, chats, nav, ai, trust, growth, uploads, subscriptions, devices, analytics, admin, admin_telegram, webhooks, websocket, safety, profile_trust, account, referrals, likes, monetization, video, onboarding, daily, verify, dev, paddle_webhook

api_router = APIRouter()
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(auth_social.router, prefix="/auth", tags=["auth"])
api_router.include_router(nav.router, prefix="/nav", tags=["nav"])
api_router.include_router(daily.router, prefix="/daily", tags=["daily"])
api_router.include_router(profiles.router, prefix="/profiles", tags=["profiles"])
api_router.include_router(verify.router, prefix="/verify", tags=["verify"])
api_router.include_router(discover.router, prefix="/discover", tags=["discover"])
api_router.include_router(swipes.router, prefix="/swipes", tags=["swipes"])
api_router.include_router(onboarding.router, prefix="/onboarding", tags=["onboarding"])
api_router.include_router(matches.router, prefix="/matches", tags=["matches"])
api_router.include_router(messages.router, prefix="/messages", tags=["messages"])
api_router.include_router(chats.router, prefix="/chats", tags=["chats"])
api_router.include_router(account.router, tags=["account"])
api_router.include_router(safety.router, prefix="/users", tags=["users"])
api_router.include_router(safety.legacy_router, prefix="/safety", tags=["safety"])
api_router.include_router(ai.router, prefix="/ai", tags=["ai"])
api_router.include_router(video.router, prefix="/video", tags=["video"])
api_router.include_router(trust.router, prefix="/trust", tags=["trust"])
api_router.include_router(profile_trust.router, tags=["trust"])
api_router.include_router(growth.router, prefix="/growth", tags=["growth"])
api_router.include_router(uploads.router, prefix="/uploads", tags=["uploads"])
api_router.include_router(subscriptions.router, prefix="/subscriptions", tags=["subscriptions"])
api_router.include_router(paddle_webhook.router, prefix="/paddle", tags=["paddle"])
api_router.include_router(devices.router, prefix="/devices", tags=["devices"])
api_router.include_router(analytics.router, prefix="/analytics", tags=["analytics"])
api_router.include_router(referrals.router, prefix="/referrals", tags=["referrals"])
api_router.include_router(likes.router, prefix="/likes", tags=["likes"])
api_router.include_router(monetization.router, prefix="/monetization", tags=["monetization"])
api_router.include_router(admin.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_telegram.router, prefix="/admin", tags=["admin-telegram"])
api_router.include_router(webhooks.router, prefix="/webhooks", tags=["webhooks"])
api_router.include_router(websocket.router, tags=["websocket"])
api_router.include_router(dev.router, prefix="/dev", tags=["dev"])
