import type { TimedReplyOption } from "../chat/api";
import type { AppLocale } from "../i18n/locales";
import { normalizeLocaleInput } from "../i18n/locales";

export type ChatFallbackPack = {
  /** Shown while waiting for AI / timed-replies (inline + panel). */
  inlineLoading: string;
  panelTitle: string;
  panelSubtitle: string;

  easyLabel: string;
  flirtyLabel: string;
  deepLabel: string;

  easySuggestion: string;
  flirtySuggestion: string;
  deepSuggestion: string;

  easyDescription: string;
  flirtyDescription: string;
  deepDescription: string;

  sendButton: string;
  editButton: string;
  moreButton: string;
  regenerateButton: string;

  premiumCta: string;
  premiumHint: string;

  replyButton: string;
  reactButton: string;
};

/** Runtime fallback for ALL app locales — never fall back to English for non-`en` UI. */
export const CHAT_FALLBACK_REPLIES = {
  en: {
    inlineLoading: "Getting suggestions…",
    panelTitle: "💡 Suggested replies",
    panelSubtitle: "You’re in control — tap Send when it feels right.",
    easyLabel: "Easy",
    flirtyLabel: "Flirty",
    deepLabel: "Deep",
    easySuggestion: "Got you 😳 what part of that matters most to you?",
    flirtySuggestion: "Okay, that’s kinda cute 😊 tell me more?",
    deepSuggestion: "Interesting — what made you feel that way?",
    easyDescription: "Low pressure — easy for them to answer.",
    flirtyDescription: "Playful warmth — fun without pushing.",
    deepDescription: "Thoughtful — shows you’re really listening.",
    sendButton: "Send",
    editButton: "Edit",
    moreButton: "More like this",
    regenerateButton: "Regenerate",
    premiumCta: "Continue",
    premiumHint: "Premium gets smarter, personalized lines here.",
    replyButton: "Reply",
    reactButton: "React",
  },
  uk: {
    inlineLoading: "Підбираємо відповіді…",
    panelTitle: "💡 Підказані відповіді",
    panelSubtitle: "Ти керуєш — натисни «Надіслати», коли відчувається доречно.",
    easyLabel: "Легко",
    flirtyLabel: "Флірт",
    deepLabel: "Глибше",
    easySuggestion: "Зрозумів 😳 а що в цьому для тебе найважливіше?",
    flirtySuggestion: "Окей, це мило 😊 розкажеш більше?",
    deepSuggestion: "Цікаво — що саме змусило тебе так відчути?",
    easyDescription: "Без тиску — їм легко відповісти.",
    flirtyDescription: "Грайливо й тепло — без нав’язливості.",
    deepDescription: "Змістовно — видно, що ти слухаєш.",
    sendButton: "Надіслати",
    editButton: "Редагувати",
    moreButton: "Ще в цьому стилі",
    regenerateButton: "Оновити",
    premiumCta: "Відкрити кращі відповіді",
    premiumHint: "У Premium тут будуть розумніші, персоналізовані фрази.",
    replyButton: "Відповісти",
    reactButton: "Реакція",
  },
  ru: {
    inlineLoading: "Подбираем ответы…",
    panelTitle: "💡 Подсказанные ответы",
    panelSubtitle: "Ты решаешь — нажми «Отправить», когда будет уместно.",
    easyLabel: "Легко",
    flirtyLabel: "Флирт",
    deepLabel: "Глубже",
    easySuggestion: "Понял 😳 а что в этом для тебя самое важное?",
    flirtySuggestion: "Окей, это мило 😊 расскажешь больше?",
    deepSuggestion: "Интересно — что именно заставило тебя так почувствовать?",
    easyDescription: "Без давления — им легко ответить.",
    flirtyDescription: "Игривое тепло — без напора.",
    deepDescription: "Вдумчиво — видно, что ты слушаешь.",
    sendButton: "Отправить",
    editButton: "Редактировать",
    moreButton: "Ещё в этом стиле",
    regenerateButton: "Обновить",
    premiumCta: "Открыть лучшие ответы",
    premiumHint: "В Premium здесь будут более умные, персонализированные фразы.",
    replyButton: "Ответить",
    reactButton: "Реакция",
  },
  es: {
    inlineLoading: "Obteniendo sugerencias…",
    panelTitle: "💡 Respuestas sugeridas",
    panelSubtitle: "Tú controlas — toca “Enviar” cuando se sienta bien.",
    easyLabel: "Fácil",
    flirtyLabel: "Coqueta",
    deepLabel: "Profunda",
    easySuggestion: "Entiendo 😳 ¿qué parte de eso es lo más importante para ti?",
    flirtySuggestion: "Ok, eso es tierno 😊 ¿me cuentas más?",
    deepSuggestion: "Interesante — ¿qué te hizo sentir así?",
    easyDescription: "Sin presión — fácil para que respondan.",
    flirtyDescription: "Calidez juguetona — divertido sin empujar.",
    deepDescription: "Reflexiva — muestra que estás escuchando de verdad.",
    sendButton: "Enviar",
    editButton: "Editar",
    moreButton: "Más como esto",
    regenerateButton: "Regenerar",
    premiumCta: "Desbloquear mejores respuestas",
    premiumHint: "Premium trae líneas más inteligentes y personalizadas aquí.",
    replyButton: "Responder",
    reactButton: "Reaccionar",
  },
  pt: {
    inlineLoading: "A buscar sugestões…",
    panelTitle: "💡 Respostas sugeridas",
    panelSubtitle: "Você controla — toque em “Enviar” quando fizer sentido.",
    easyLabel: "Fácil",
    flirtyLabel: "Paquera",
    deepLabel: "Profundo",
    easySuggestion: "Entendi 😳 o que nisso é mais importante para você?",
    flirtySuggestion: "Ok, isso é fofo 😊 me conta mais?",
    deepSuggestion: "Interessante — o que fez você se sentir assim?",
    easyDescription: "Sem pressão — fácil para a outra pessoa responder.",
    flirtyDescription: "Calor brincalhão — divertido sem forçar.",
    deepDescription: "Atencioso — mostra que você está ouvindo de verdade.",
    sendButton: "Enviar",
    editButton: "Editar",
    moreButton: "Mais desse estilo",
    regenerateButton: "Gerar de novo",
    premiumCta: "Desbloquear respostas melhores",
    premiumHint: "No Premium, você vê aqui frases mais inteligentes e personalizadas.",
    replyButton: "Responder",
    reactButton: "Reagir",
  },
  fr: {
    inlineLoading: "Récupération des suggestions…",
    panelTitle: "💡 Réponses suggérées",
    panelSubtitle: "C’est toi qui décides — appuie sur « Envoyer » quand ça te convient.",
    easyLabel: "Léger",
    flirtyLabel: "Taquin",
    deepLabel: "Plus profond",
    easySuggestion: "Je vois 😳 c’est quoi la partie la plus importante pour toi ?",
    flirtySuggestion: "Ok, c’est mignon 😊 tu m’en dis plus ?",
    deepSuggestion: "Intéressant — qu’est-ce qui t’a fait ressentir ça ?",
    easyDescription: "Sans pression — facile à répondre.",
    flirtyDescription: "Chaleur ludique — fun sans insister.",
    deepDescription: "Réfléchi — on sent que tu écoutes vraiment.",
    sendButton: "Envoyer",
    editButton: "Modifier",
    moreButton: "Plus comme ça",
    regenerateButton: "Regénérer",
    premiumCta: "Débloquer de meilleures réponses",
    premiumHint: "Avec Premium, des phrases plus intelligentes et personnalisées ici.",
    replyButton: "Répondre",
    reactButton: "Réagir",
  },
  de: {
    inlineLoading: "Vorschläge werden geladen…",
    panelTitle: "💡 Vorgeschlagene Antworten",
    panelSubtitle: "Du entscheidest — tippe auf „Senden“, wenn es sich richtig anfühlt.",
    easyLabel: "Locker",
    flirtyLabel: "Flirt",
    deepLabel: "Tiefer",
    easySuggestion: "Verstehe 😳 was davon ist dir am wichtigsten?",
    flirtySuggestion: "Okay, das ist süß 😊 erzähl mehr?",
    deepSuggestion: "Interessant — was hat dich so fühlen lassen?",
    easyDescription: "Ohne Druck — leicht zu beantworten.",
    flirtyDescription: "Verspielte Wärme — spaßig ohne Druck.",
    deepDescription: "Nachdenklich — zeigt, dass du wirklich zuhörst.",
    sendButton: "Senden",
    editButton: "Bearbeiten",
    moreButton: "Mehr in dem Stil",
    regenerateButton: "Neu erzeugen",
    premiumCta: "Bessere Antworten freischalten",
    premiumHint: "Mit Premium gibt’s hier intelligentere, persönlichere Zeilen.",
    replyButton: "Antworten",
    reactButton: "Reagieren",
  },
  it: {
    inlineLoading: "Sto preparando i suggerimenti…",
    panelTitle: "💡 Risposte suggerite",
    panelSubtitle: "Comandi tu — tocca «Invia» quando ti sembra giusto.",
    easyLabel: "Leggera",
    flirtyLabel: "Flirt",
    deepLabel: "Profonda",
    easySuggestion: "Capito 😳 cosa è più importante per te in questo?",
    flirtySuggestion: "Ok, è carino 😊 mi racconti di più?",
    deepSuggestion: "Interessante — cosa ti ha fatto sentire così?",
    easyDescription: "Senza pressione — facile da rispondere.",
    flirtyDescription: "Calore giocoso — divertente senza insistere.",
    deepDescription: "Riflessiva — si nota che ascolti davvero.",
    sendButton: "Invia",
    editButton: "Modifica",
    moreButton: "Altro così",
    regenerateButton: "Rigenera",
    premiumCta: "Sblocca risposte migliori",
    premiumHint: "Con Premium qui trovi frasi più intelligenti e personalizzate.",
    replyButton: "Rispondi",
    reactButton: "Reagisci",
  },
  pl: {
    inlineLoading: "Ładowanie podpowiedzi…",
    panelTitle: "💡 Sugerowane odpowiedzi",
    panelSubtitle: "Ty decydujesz — naciśnij «Wyślij», kiedy czujesz, że to dobry moment.",
    easyLabel: "Lekko",
    flirtyLabel: "Flirt",
    deepLabel: "Głębiej",
    easySuggestion: "Rozumiem 😳 co z tego jest dla ciebie najważniejsze?",
    flirtySuggestion: "Spoko, to słodkie 😊 opowiesz więcej?",
    deepSuggestion: "Ciekawe — co sprawiło, że tak się poczułaś/poczułeś?",
    easyDescription: "Bez presji — łatwo odpowiedzieć.",
    flirtyDescription: "Figlarnie i ciepło — zabawnie, bez pchania.",
    deepDescription: "Przemyślanie — widać, że naprawdę słuchasz.",
    sendButton: "Wyślij",
    editButton: "Edytuj",
    moreButton: "Więcej w tym stylu",
    regenerateButton: "Wygeneruj ponownie",
    premiumCta: "Odblokuj lepsze odpowiedzi",
    premiumHint: "W Premium zobaczysz tu mądrzejsze, spersonalizowane zdania.",
    replyButton: "Odpowiedz",
    reactButton: "Zareaguj",
  },
  tr: {
    inlineLoading: "Öneriler yükleniyor…",
    panelTitle: "💡 Önerilen yanıtlar",
    panelSubtitle: "Kontrol sende — doğru hissedince «Gönder»e dokun.",
    easyLabel: "Rahat",
    flirtyLabel: "Flört",
    deepLabel: "Derin",
    easySuggestion: "Anladım 😳 senin için en önemli kısmı ne?",
    flirtySuggestion: "Tamam, bu tatlı 😊 biraz daha anlatır mısın?",
    deepSuggestion: "İlginç — seni böyle hissettiren ne oldu?",
    easyDescription: "Baskı yok — cevaplaması kolay.",
    flirtyDescription: "Oyunbaz sıcaklık — zorlamadan eğlenceli.",
    deepDescription: "Düşünceli — gerçekten dinlediğin belli.",
    sendButton: "Gönder",
    editButton: "Düzenle",
    moreButton: "Bunun gibi daha",
    regenerateButton: "Yeniden üret",
    premiumCta: "Daha iyi yanıtların kilidini aç",
    premiumHint: "Premium ile burada daha akıllı, kişisel cümleler görürsün.",
    replyButton: "Yanıtla",
    reactButton: "Tepki ver",
  },
  "zh-CN": {
    inlineLoading: "正在获取建议…",
    panelTitle: "💡 建议回复",
    panelSubtitle: "由你主导——感觉对了再点「发送」。",
    easyLabel: "轻松",
    flirtyLabel: "暧昧",
    deepLabel: "走心",
    easySuggestion: "懂了😳 对你来说这里最重要的是哪一点？",
    flirtySuggestion: "好吧，有点可爱😊 再多说点？",
    deepSuggestion: "有意思——是什么让你有这种感觉？",
    easyDescription: "不施压——对方好接。",
    flirtyDescription: "俏皮又温暖——好玩但不推进过猛。",
    deepDescription: "有思考感——让人知道你在认真听。",
    sendButton: "发送",
    editButton: "编辑",
    moreButton: "再来点类似的",
    regenerateButton: "重新生成",
    premiumCta: "解锁更好的回复",
    premiumHint: "Premium 会在这里给你更聪明、更个性化的句子。",
    replyButton: "回复",
    reactButton: "反应",
  },
  "zh-TW": {
    inlineLoading: "正在取得建議…",
    panelTitle: "💡 建議回覆",
    panelSubtitle: "由你主導——感覺對了再點「傳送」。",
    easyLabel: "輕鬆",
    flirtyLabel: "曖昧",
    deepLabel: "走心",
    easySuggestion: "懂了😳 對你來說哪一點最重要？",
    flirtySuggestion: "好吧，有點可愛😊 再多說一點？",
    deepSuggestion: "有意思——是什麼讓你有這種感覺？",
    easyDescription: "不施壓——對方好回。",
    flirtyDescription: "俏皮又溫暖——好玩但不推進過猛。",
    deepDescription: "有思考感——讓人知道你在認真聽。",
    sendButton: "傳送",
    editButton: "編輯",
    moreButton: "再來點類似的",
    regenerateButton: "重新產生",
    premiumCta: "解鎖更好的回覆",
    premiumHint: "Premium 會在這裡給你更聰明、更個人化的句子。",
    replyButton: "回覆",
    reactButton: "反應",
  },
  ja: {
    inlineLoading: "候補を取得中…",
    panelTitle: "💡 返信候補",
    panelSubtitle: "主導権はあなたに。しっくりきたら「送信」をタップ。",
    easyLabel: "ライト",
    flirtyLabel: "ちょい甘",
    deepLabel: "深め",
    easySuggestion: "なるほど😳 その中で一番大事なのってどこ？",
    flirtySuggestion: "それ、ちょっと可愛いね😊 もう少し聞かせて？",
    deepSuggestion: "興味深いね — そう感じたきっかけって何だったの？",
    easyDescription: "圧少なめ — 相手が返しやすい。",
    flirtyDescription: "遊び心のある温かさ — 押しすぎない。",
    deepDescription: "ちゃんと聞いてる感じ — 一歩深く。",
    sendButton: "送信",
    editButton: "編集",
    moreButton: "この感じでもっと",
    regenerateButton: "再生成",
    premiumCta: "もっと良い返信を解放",
    premiumHint: "Premium ならここに、より賢くパーソナライズされた文が出ます。",
    replyButton: "返信",
    reactButton: "リアクション",
  },
  ko: {
    inlineLoading: "추천 답장을 불러오는 중…",
    panelTitle: "💡 추천 답장",
    panelSubtitle: "주도권은 당신에게 있어요 — 마음에 들 때 «보내기»를 눌러요.",
    easyLabel: "가벼운",
    flirtyLabel: "살짝 설렘",
    deepLabel: "깊은",
    easySuggestion: "알겠어 😳 그중에서 너한테 제일 중요한 건 뭐야?",
    flirtySuggestion: "그거 좀 귀엽다 😊 조금만 더 얘기해줄래?",
    deepSuggestion: "흥미롭다 — 그렇게 느끼게 된 이유가 뭐였어?",
    easyDescription: "부담 적게 — 상대가 답하기 쉬워요.",
    flirtyDescription: "장난스럽고 따뜻하게 — 밀어붙이지 않고.",
    deepDescription: "생각이 느껴져 — 진짜 듣고 있다는 느낌.",
    sendButton: "보내기",
    editButton: "편집",
    moreButton: "비슷한 톤으로 더",
    regenerateButton: "다시 생성",
    premiumCta: "더 좋은 답장 잠금 해제",
    premiumHint: "프리미엄이면 여기서 더 똑똑하고 개인화된 문장을 볼 수 있어요.",
    replyButton: "답장",
    reactButton: "반응",
  },
  hi: {
    inlineLoading: "सुझाव लोड हो रहे हैं…",
    panelTitle: "💡 सुझाई गई जवाब",
    panelSubtitle: "नियंत्रण आपके पास है — सही लगे तो «भेजें» दबाएँ।",
    easyLabel: "हल्का",
    flirtyLabel: "फ्लर्टी",
    deepLabel: "गहरा",
    easySuggestion: "समझा 😳 इसमें तुम्हारे लिए सबसे ज़रूरी हिस्सा कौन सा है?",
    flirtySuggestion: "ठीक है, ये प्यारा है 😊 थोड़ा और बताओगे?",
    deepSuggestion: "दिलचस्प — ऐसा महसूस करने की वजह क्या रही?",
    easyDescription: "दबाव नहीं — जवाब देना आसान।",
    flirtyDescription: "चंचल गर्मजोशी — ज़बरदस्ती नहीं।",
    deepDescription: "सोच समझकर — साफ़ दिखता है कि तुम सुन रहे हो।",
    sendButton: "भेजें",
    editButton: "संपादित करें",
    moreButton: "ऐसा ही और",
    regenerateButton: "फिर से बनाएँ",
    premiumCta: "बेहतर जवाब अनलॉक करें",
    premiumHint: "प्रीमियम में यहाँ ज़्यादा स्मार्ट, निजी लाइनें मिलती हैं।",
    replyButton: "जवाब",
    reactButton: "प्रतिक्रिया",
  },
  id: {
    inlineLoading: "Mengambil saran…",
    panelTitle: "💡 Balasan yang disarankan",
    panelSubtitle: "Kamu yang pegang kendali — ketuk «Kirim» kalau sudah pas.",
    easyLabel: "Santai",
    flirtyLabel: "Genit",
    deepLabel: "Mendalam",
    easySuggestion: "Oke, paham 😳 bagian mana yang paling penting buat kamu?",
    flirtySuggestion: "Oke, itu lucu 😊 mau cerita lagi?",
    deepSuggestion: "Menarik — apa yang bikin kamu merasa begitu?",
    easyDescription: "Tanpa tekanan — gampang dibalas.",
    flirtyDescription: "Hangat main-main — seru tanpa memaksa.",
    deepDescription: "Penuh pikiran — keliatan kamu benar-benar mendengar.",
    sendButton: "Kirim",
    editButton: "Edit",
    moreButton: "Lagi yang mirip",
    regenerateButton: "Buat ulang",
    premiumCta: "Buka balasan lebih baik",
    premiumHint: "Premium dapat kalimat lebih pintar dan personal di sini.",
    replyButton: "Balas",
    reactButton: "Reaksi",
  },
  vi: {
    inlineLoading: "Đang tải gợi ý…",
    panelTitle: "💡 Gợi ý trả lời",
    panelSubtitle: "Bạn là người chủ động — chạm «Gửi» khi thấy hợp.",
    easyLabel: "Nhẹ",
    flirtyLabel: "Tinh nghịch",
    deepLabel: "Sâu",
    easySuggestion: "Hiểu rồi 😳 phần nào quan trọng nhất với bạn?",
    flirtySuggestion: "Ổn, dễ thương đấy 😊 kể thêm chút nhé?",
    deepSuggestion: "Thú vị — điều gì khiến bạn cảm thấy vậy?",
    easyDescription: "Không áp lực — dễ trả lời.",
    flirtyDescription: "Ấm áp tinh nghịch — vui mà không ép.",
    deepDescription: "Chân thành — thấy rõ bạn đang lắng nghe.",
    sendButton: "Gửi",
    editButton: "Sửa",
    moreButton: "Thêm kiểu này",
    regenerateButton: "Tạo lại",
    premiumCta: "Mở khóa câu trả lời hay hơn",
    premiumHint: "Premium có câu thông minh và cá nhân hóa hơn ở đây.",
    replyButton: "Trả lời",
    reactButton: "Phản ứng",
  },
  th: {
    inlineLoading: "กำลังโหลดคำแนะนำ…",
    panelTitle: "💡 คำตอบแนะนำ",
    panelSubtitle: "คุณเป็นคนกำหนด — แตะ «ส่ง» เมื่อรู้สึกพอดี",
    easyLabel: "เบา ๆ",
    flirtyLabel: "หยอกล้อ",
    deepLabel: "ลึก",
    easySuggestion: "เข้าใจแล้ว 😳 ส่วนไหนสำคัญที่สุดสำหรับคุณ?",
    flirtySuggestion: "โอเค น่ารักนะ 😊 เล่าเพิ่มหน่อยได้ไหม?",
    deepSuggestion: "น่าสนใจ — อะไรทำให้คุณรู้สึกแบบนั้น?",
    easyDescription: "ไม่กดดัน — ตอบง่าย.",
    flirtyDescription: "อบอุ่นแบบขี้เล่น — สนุกโดยไม่เบียดเบียน.",
    deepDescription: "ตั้งใจฟัง — เห็นว่าคุณใส่ใจจริง ๆ.",
    sendButton: "ส่ง",
    editButton: "แก้ไข",
    moreButton: "แบบนี้อีก",
    regenerateButton: "สร้างใหม่",
    premiumCta: "ปลดล็อกคำตอบที่ดีขึ้น",
    premiumHint: "พรีเมียมได้ประโยคที่ฉลาดและเป็นส่วนตัวมากขึ้นที่นี่.",
    replyButton: "ตอบกลับ",
    reactButton: "รีแอ็กชัน",
  },
  ar: {
    inlineLoading: "جارٍ جلب الاقتراحات…",
    panelTitle: "💡 ردود مقترحة",
    panelSubtitle: "القرار لك — اضغط «إرسال» عندما يبدو مناسبًا.",
    easyLabel: "خفيف",
    flirtyLabel: "مغازل",
    deepLabel: "أعمق",
    easySuggestion: "فهمت 😳 أي جزء من هذا الأهم بالنسبة لك؟",
    flirtySuggestion: "حلو، هذا لطيف 😊 تحب تحكي لي أكثر؟",
    deepSuggestion: "مثير للاهتمام — ما الذي جعلك تشعر هكذا؟",
    easyDescription: "بدون ضغط — يسهل الرد.",
    flirtyDescription: "دفء مرح — ممتع دون إلحاح.",
    deepDescription: "بعمق — يظهر أنك تستمع فعلًا.",
    sendButton: "إرسال",
    editButton: "تعديل",
    moreButton: "المزيد بنفس الأسلوب",
    regenerateButton: "إعادة الإنشاء",
    premiumCta: "افتح ردودًا أفضل",
    premiumHint: "مع Premium تظهر هنا جمل أذكى وأكثر تخصيصًا.",
    replyButton: "رد",
    reactButton: "تفاعل",
  },
  he: {
    inlineLoading: "טוען הצעות…",
    panelTitle: "💡 תשובות מוצעות",
    panelSubtitle: "אתה בשליטה — הקש «שלח» כשמרגיש נכון.",
    easyLabel: "קליל",
    flirtyLabel: "פלרטטני",
    deepLabel: "עמוק",
    easySuggestion: "הבנתי 😳 מה הכי חשוב לך כאן?",
    flirtySuggestion: "אוקיי, זה חמוד 😊 תספר/י עוד קצת?",
    deepSuggestion: "מעניין — מה גרם לך להרגיש ככה?",
    easyDescription: "בלי לחץ — קל להגיב.",
    flirtyDescription: "חמימות שובבית — כיף בלי לדחוף.",
    deepDescription: "מעמיק — רואים שבאמת מאזינים.",
    sendButton: "שלח",
    editButton: "ערוך",
    moreButton: "עוד באותו סגנון",
    regenerateButton: "צור מחדש",
    premiumCta: "שחרר תשובות טובות יותר",
    premiumHint: "בפרימיום תראה כאן שורות חכמות ומותאמות אישית יותר.",
    replyButton: "השב",
    reactButton: "תגובה",
  },
  bg: {
    inlineLoading: "Зареждаме предложения…",
    panelTitle: "💡 Предложени отговори",
    panelSubtitle: "Ти решаваш — натисни „Изпрати“, когато е ок.",
    easyLabel: "Леко",
    flirtyLabel: "Флирт",
    deepLabel: "По-дълбоко",
    easySuggestion: "Разбирам 😳 коя част е най-важна за теб?",
    flirtySuggestion: "Окей, това е сладко 😊 ще ми разкажеш още?",
    deepSuggestion: "Интересно — какво те накара да се почувстваш така?",
    easyDescription: "Без напрежение — лесно е да отговорят.",
    flirtyDescription: "Игриво и топло — забавно без натиск.",
    deepDescription: "Смислено — личи, че слушаш наистина.",
    sendButton: "Изпрати",
    editButton: "Редактирай",
    moreButton: "Още такива",
    regenerateButton: "Генерирай отново",
    premiumCta: "Отключи по-добри отговори",
    premiumHint: "С Premium тук ще получиш по-умни, персонализирани реплики.",
    replyButton: "Отговори",
    reactButton: "Реакция",
  },
  nl: {
    inlineLoading: "Suggesties laden…",
    panelTitle: "💡 Voorgestelde antwoorden",
    panelSubtitle: "Jij bepaalt — tik op «Verstuur» als het goed voelt.",
    easyLabel: "Licht",
    flirtyLabel: "Flirt",
    deepLabel: "Dieper",
    easySuggestion: "Snap ik 😳 wat is daar het belangrijkst voor jou?",
    flirtySuggestion: "Oké, dat is schattig 😊 vertel je meer?",
    deepSuggestion: "Interessant — wat deed je zo voelen?",
    easyDescription: "Geen druk — makkelijk te beantwoorden.",
    flirtyDescription: "Speelse warmte — leuk zonder te pushen.",
    deepDescription: "Doordacht — laat zien dat je echt luistert.",
    sendButton: "Verstuur",
    editButton: "Bewerk",
    moreButton: "Meer zo",
    regenerateButton: "Opnieuw genereren",
    premiumCta: "Betere antwoorden ontgrendelen",
    premiumHint: "Met Premium krijg je hier slimmere, persoonlijkere zinnen.",
    replyButton: "Antwoord",
    reactButton: "Reageer",
  },
  sv: {
    inlineLoading: "Hämtar förslag…",
    panelTitle: "💡 Föreslagna svar",
    panelSubtitle: "Du bestämmer — tryck på «Skicka» när det känns rätt.",
    easyLabel: "Lätt",
    flirtyLabel: "Flörtig",
    deepLabel: "Djup",
    easySuggestion: "Fattar 😳 vad är viktigast för dig i det?",
    flirtySuggestion: "Okej, det där är gulligt 😊 berättar du mer?",
    deepSuggestion: "Intressant — vad fick dig att känna så?",
    easyDescription: "Utan press — lätt att svara på.",
    flirtyDescription: "Lekfull värme — kul utan att pusha.",
    deepDescription: "Eftertänksamt — syns att du verkligen lyssnar.",
    sendButton: "Skicka",
    editButton: "Redigera",
    moreButton: "Mer i samma stil",
    regenerateButton: "Generera igen",
    premiumCta: "Lås upp bättre svar",
    premiumHint: "Med Premium får du smartare, mer personliga rader här.",
    replyButton: "Svara",
    reactButton: "Reagera",
  },
  cs: {
    inlineLoading: "Načítám návrhy…",
    panelTitle: "💡 Navrhované odpovědi",
    panelSubtitle: "Ty máš kontrolu — klepni na «Odeslat», až to dává smysl.",
    easyLabel: "Lehce",
    flirtyLabel: "Flirt",
    deepLabel: "Hlouběji",
    easySuggestion: "Chápu 😳 co z toho je pro tebe nejdůležitější?",
    flirtySuggestion: "Ok, to je roztomilé 😊 povíš víc?",
    deepSuggestion: "Zajímavé — co tě nutilo to tak cítit?",
    easyDescription: "Bez tlaku — snadné odpovědět.",
    flirtyDescription: "Hravé teplo — zábava bez nátlaku.",
    deepDescription: "Promyšlené — je vidět, že opravdu posloucháš.",
    sendButton: "Odeslat",
    editButton: "Upravit",
    moreButton: "Víc v tomhle stylu",
    regenerateButton: "Znovu vygenerovat",
    premiumCta: "Odemknout lepší odpovědi",
    premiumHint: "S Premium uvidíš tu chytřejší, personalizované věty.",
    replyButton: "Odpovědět",
    reactButton: "Reagovat",
  },
  ro: {
    inlineLoading: "Se încarcă sugestiile…",
    panelTitle: "💡 Răspunsuri sugerate",
    panelSubtitle: "Tu decizi — apasă «Trimite» când simți că e potrivit.",
    easyLabel: "Ușor",
    flirtyLabel: "Flirt",
    deepLabel: "Profund",
    easySuggestion: "Am înțeles 😳 ce parte contează cel mai mult pentru tine?",
    flirtySuggestion: "Ok, e drăguț 😊 îmi spui mai mult?",
    deepSuggestion: "Interesant — ce te-a făcut să simți așa?",
    easyDescription: "Fără presiune — ușor de răspuns.",
    flirtyDescription: "Căldură jucăușă — distractiv fără să împingi.",
    deepDescription: "Cu gândire — se vede că asculți cu adevărat.",
    sendButton: "Trimite",
    editButton: "Editează",
    moreButton: "Mai mult așa",
    regenerateButton: "Regenerează",
    premiumCta: "Deblochează răspunsuri mai bune",
    premiumHint: "Cu Premium vezi aici propoziții mai inteligente și personalizate.",
    replyButton: "Răspunde",
    reactButton: "Reacționează",
  },
  hu: {
    inlineLoading: "Javaslatok betöltése…",
    panelTitle: "💡 Javasolt válaszok",
    panelSubtitle: "Te irányítasz — koppints a «Küldésre», ha jónak érzed.",
    easyLabel: "Könnyű",
    flirtyLabel: "Flört",
    deepLabel: "Mély",
    easySuggestion: "Értem 😳 mi a legfontosabb neked ebben?",
    flirtySuggestion: "Oké, ez cuki 😊 mesélsz még?",
    deepSuggestion: "Érdekes — miért érezted így?",
    easyDescription: "Nyomás nélkül — könnyű válaszolni.",
    flirtyDescription: "Játékos melegség — mókás, nem tolakodó.",
    deepDescription: "Átgondolt — látszik, hogy tényleg figyelsz.",
    sendButton: "Küldés",
    editButton: "Szerkesztés",
    moreButton: "Még ilyen stílusban",
    regenerateButton: "Újragenerálás",
    premiumCta: "Jobb válaszok feloldása",
    premiumHint: "Prémium mellett okosabb, személyre szabott mondatok jelennek meg itt.",
    replyButton: "Válasz",
    reactButton: "Reakció",
  },
  el: {
    inlineLoading: "Φόρτωση προτάσεων…",
    panelTitle: "💡 Προτεινόμενες απαντήσεις",
    panelSubtitle: "Εσύ αποφασίζεις — πάτα «Αποστολή» όταν νιώθεις σωστά.",
    easyLabel: "Ελαφρύ",
    flirtyLabel: "Φλερτ",
    deepLabel: "Βαθύ",
    easySuggestion: "Κατάλαβα 😳 ποιο κομμάτι είναι το πιο σημαντικό για σένα;",
    flirtySuggestion: "Οκ, είναι χαριτωμένο 😊 θα μου πεις λίγο ακόμα;",
    deepSuggestion: "Ενδιαφέρον — τι σε έκανε να το νιώσεις έτσι;",
    easyDescription: "Χωρίς πίεση — εύκολο να απαντήσει.",
    flirtyDescription: "Παιχνιδιάρικη ζεστασιά — διασκεδαστικό χωρίς πίεση.",
    deepDescription: "Σκεπτικό — φαίνεται ότι ακούς πραγματικά.",
    sendButton: "Αποστολή",
    editButton: "Επεξεργασία",
    moreButton: "Κι άλλα έτσι",
    regenerateButton: "Επανάληψη δημιουργίας",
    premiumCta: "Ξεκλείδωμα καλύτερων απαντήσεων",
    premiumHint: "Με Premium εμφανίζονται εδώ πιο έξυπνες, εξατομικευμένες φράσεις.",
    replyButton: "Απάντηση",
    reactButton: "Αντίδραση",
  },
  da: {
    inlineLoading: "Henter forslag…",
    panelTitle: "💡 Foreslåede svar",
    panelSubtitle: "Du bestemmer — tryk «Send», når det føles rigtigt.",
    easyLabel: "Let",
    flirtyLabel: "Flirtende",
    deepLabel: "Dyb",
    easySuggestion: "Forstår 😳 hvad er vigtigst for dig der?",
    flirtySuggestion: "Okay, det er sødt 😊 vil du fortælle mere?",
    deepSuggestion: "Interessant — hvad fik dig til at føle sådan?",
    easyDescription: "Uden pres — nemt at svare på.",
    flirtyDescription: "Legende varme — sjovt uden at skubbe.",
    deepDescription: "Omtænksomt — man kan se, du lytter.",
    sendButton: "Send",
    editButton: "Rediger",
    moreButton: "Mere i samme stil",
    regenerateButton: "Generér igen",
    premiumCta: "Lås bedre svar op",
    premiumHint: "Med Premium får du klogere, mere personlige linjer her.",
    replyButton: "Svar",
    reactButton: "Reager",
  },
  fi: {
    inlineLoading: "Ladataan ehdotuksia…",
    panelTitle: "💡 Ehdotetut vastaukset",
    panelSubtitle: "Sinä päätät — napauta «Lähetä», kun tuntuu oikealta.",
    easyLabel: "Kevyt",
    flirtyLabel: "Flirttaileva",
    deepLabel: "Syvä",
    easySuggestion: "Ymmärrän 😳 mikä siinä on sulle tärkeintä?",
    flirtySuggestion: "Okei, toi on söpö 😊 kerrotko lisää?",
    deepSuggestion: "Mielenkiintoista — mikä sai sut tuntemaan noin?",
    easyDescription: "Ilman painetta — helppo vastata.",
    flirtyDescription: "Leikkisä lämpö — hauskaa ilman työntämistä.",
    deepDescription: "Harkittu — näkyy että kuuntelet oikeasti.",
    sendButton: "Lähetä",
    editButton: "Muokkaa",
    moreButton: "Lisää samalla tyylillä",
    regenerateButton: "Luo uudelleen",
    premiumCta: "Avaa parempia vastauksia",
    premiumHint: "Premiumilla näet tässä älykkäämpiä, henkilökohtaisempia lauseita.",
    replyButton: "Vastaa",
    reactButton: "Reagoi",
  },
  no: {
    inlineLoading: "Henter forslag…",
    panelTitle: "💡 Foreslåtte svar",
    panelSubtitle: "Du bestemmer — trykk «Send» når det føles riktig.",
    easyLabel: "Lett",
    flirtyLabel: "Flørtete",
    deepLabel: "Dyp",
    easySuggestion: "Skjønner 😳 hva er viktigst for deg der?",
    flirtySuggestion: "Greit, det er søtt 😊 vil du si litt mer?",
    deepSuggestion: "Interessant — hva fikk deg til å føle sånn?",
    easyDescription: "Uten press — lett å svare på.",
    flirtyDescription: "Leken varme — gøy uten å presse.",
    deepDescription: "Omsorgsfullt — man ser at du lytter.",
    sendButton: "Send",
    editButton: "Rediger",
    moreButton: "Mer i samme stil",
    regenerateButton: "Generer på nytt",
    premiumCta: "Lås opp bedre svar",
    premiumHint: "Med Premium får du smartere, mer personlige linjer her.",
    replyButton: "Svar",
    reactButton: "Reager",
  },
} as const satisfies Record<AppLocale, ChatFallbackPack>;

export function getChatFallbackPack(locale: AppLocale | string | null | undefined): ChatFallbackPack {
  const normalized = normalizeLocaleInput(String(locale ?? ""));
  const key = (normalized ?? "en") as AppLocale;
  return CHAT_FALLBACK_REPLIES[key];
}

export function timedReplyFallbackTriplet(pack: ChatFallbackPack): TimedReplyOption[] {
  return [
    { style: "light", text: pack.easySuggestion },
    { style: "flirty", text: pack.flirtySuggestion },
    { style: "deep", text: pack.deepSuggestion },
  ];
}

export function styleMetaFromPack(pack: ChatFallbackPack, style: TimedReplyOption["style"]): { label: string; hint: string } {
  if (style === "light") return { label: pack.easyLabel, hint: pack.easyDescription };
  if (style === "flirty") return { label: pack.flirtyLabel, hint: pack.flirtyDescription };
  return { label: pack.deepLabel, hint: pack.deepDescription };
}

export function copilotFallbackFromPack(pack: ChatFallbackPack): { label: string; text: string }[] {
  return [
    { label: pack.easyLabel, text: pack.easySuggestion },
    { label: pack.flirtyLabel, text: pack.flirtySuggestion },
    { label: pack.deepLabel, text: pack.deepSuggestion },
  ];
}
